Update onIdentify config parameter
evcc-io/docs pull request #15
Opened 2021-12-04 18:34 UTC by rivengh

* vehicle: add optional parameter `onIdentify`
* loadpoint: remove deprecated parameters `onDisconnect` and `onIdentify`
* loadpoint: updated description of `resetOnDisconnect` parameter

2021-12-04 19:15 UTC, premultiply approved these changes

2021-12-04 19:21 UTC, premultiply requested changes

2021-12-04 19:21 UTC, premultiply commented on docs/reference/configuration/loadpoints.md
> +* [`soc.min`](loadpoints#min)
Hier nicht besser minSoc?

2021-12-04 19:21 UTC, premultiply commented on docs/reference/configuration/loadpoints.md
> +* [`soc.target`](loadpoints#target)
Hier nicht besser targetSoc?

2021-12-05 09:19 UTC, rivengh commented on docs/reference/configuration/loadpoints.md
> +* [`soc.min`](loadpoints#min)
Ich wollte hier beim Wording der Loadpoint Konfiguration bleiben. Da gibt es den Parameter `minSoC` ja nicht, sondern nur `min` innerhalb der `soc` Struktur.

2021-12-05 09:20 UTC, rivengh commented on docs/reference/configuration/loadpoints.md
> +* [`soc.target`](loadpoints#target)
Ich wollte hier beim Wording der Loadpoint Konfiguration bleiben. Da gibt es den Parameter `targetSoC` ja nicht, sondern nur `target` innerhalb der `soc` Struktur.

2021-12-05 09:44 UTC, merged