I18n en translations reference
evcc-io/docs pull request #425
Opened 2023-08-13 13:20 UTC by carygravel

This is still a work in progress. Just wanted to be transparent about how far I had got.

2023-08-13 14:09 UTC, duckfullstop commented
Could you rebase onto main without my commits? Should keep things a little tidier, especially as you're touching a section of the documentation that I haven't.

2023-08-15 16:16 UTC, carygravel commented
That's reference finished, I think. Please take a look!

2023-08-20 21:14 UTC, duckfullstop requested changes
Pending the given changes this'll be a LGTM.

2023-09-10 07:42 UTC, naltatis commented on i18n/en/docusaurus-plugin-content-docs/current/reference/configuration/index.md
> +See https://docs.evcc.io/docs/reference/configuration/loadpoints for more
Yes, this should definitly be a relative link like this: 

```suggestion
See [`loadpoints`](./loadpoints)
```

2023-09-10 07:43 UTC, naltatis commented
Looks very nice! Do you have anything beside the linking comments open? Otherwise I would merge this.

2023-09-10 07:46 UTC, naltatis approved these changes

2023-09-11 22:22 UTC, duckfullstop commented
@carygravel Any idea what state this is in at the moment? Could just merge this and then tackle the links in a separate issue

2023-09-13 15:57 UTC, naltatis commented
@carygravel As suggested by @duckfullstop, I'll merge this now and we can update in smaller increments from there.

2023-09-13 15:57 UTC, merged